// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.edgebud.business.project;

import com.edgebud.business.project.ProjectIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ProjectIntegrationTest_Roo_Configurable {
    
    declare @type: ProjectIntegrationTest: @Configurable;
    
}
