// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.edgebud.business.project;

import com.edgebud.business.company.Company;
import com.edgebud.business.project.Project;
import com.edgebud.business.project.ProjectDataOnDemand;
import com.edgebud.business.project.ProjectStatus;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ProjectDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProjectDataOnDemand: @Component;
    
    private Random ProjectDataOnDemand.rnd = new SecureRandom();
    
    private List<Project> ProjectDataOnDemand.data;
    
    public Project ProjectDataOnDemand.getNewTransientProject(int index) {
        Project obj = new Project();
        setCompany(obj, index);
        setCreated(obj, index);
        setDescription(obj, index);
        setId(obj, index);
        setImageUrl(obj, index);
        setName(obj, index);
        setStatus(obj, index);
        setVideoUrl(obj, index);
        return obj;
    }
    
    public void ProjectDataOnDemand.setCompany(Project obj, int index) {
        Company company = null;
        obj.setCompany(company);
    }
    
    public void ProjectDataOnDemand.setCreated(Project obj, int index) {
        Date created = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreated(created);
    }
    
    public void ProjectDataOnDemand.setDescription(Project obj, int index) {
        String description = "description_" + index;
        if (description.length() > 8192) {
            description = description.substring(0, 8192);
        }
        obj.setDescription(description);
    }
    
    public void ProjectDataOnDemand.setId(Project obj, int index) {
        String id = "id_" + index;
        obj.setId(id);
    }
    
    public void ProjectDataOnDemand.setImageUrl(Project obj, int index) {
        String imageUrl = "imageUrl_" + index;
        obj.setImageUrl(imageUrl);
    }
    
    public void ProjectDataOnDemand.setName(Project obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void ProjectDataOnDemand.setStatus(Project obj, int index) {
        ProjectStatus status = ProjectStatus.class.getEnumConstants()[0];
        obj.setStatus(status);
    }
    
    public void ProjectDataOnDemand.setVideoUrl(Project obj, int index) {
        String videoUrl = "videoUrl_" + index;
        obj.setVideoUrl(videoUrl);
    }
    
    public Project ProjectDataOnDemand.getSpecificProject(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Project obj = data.get(index);
        Long id = obj.getId_();
        return Project.findProject(id);
    }
    
    public Project ProjectDataOnDemand.getRandomProject() {
        init();
        Project obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId_();
        return Project.findProject(id);
    }
    
    public boolean ProjectDataOnDemand.modifyProject(Project obj) {
        return false;
    }
    
    public void ProjectDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Project.findProjectEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Project' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Project>();
        for (int i = 0; i < 10; i++) {
            Project obj = getNewTransientProject(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
